"""Accessible local compliance workflow shell."""

# Static markup is intentionally compact and grouped by workflow.
# ruff: noqa: E501


def compliance_page() -> str:
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/workshop.css"><script src="/assets/compliance.js" defer></script><title>Brand compliance</title></head><body><a class="skip-link" href="#main-content">Skip to main content</a><header><a href="/">Brand System Maker</a><nav aria-label="Primary"><a href="/brand-systems">Living brands</a><a href="/compliance" aria-current="page">Compliance</a></nav></header><main id="main-content">
<section class="intro"><p class="eyebrow">Evidence, not vibes</p><h1>Check a brand artifact</h1><p>Deterministic findings and model judgment are labeled separately. Unsupported checks remain visible.</p></section>
<form id="artifact-form"><label for="brand-id">Published brand system ID</label><input id="brand-id" required maxlength="36" placeholder="00000000-0000-0000-0000-000000000000"><label for="brand-version">Published brand version</label><input id="brand-version" required value="1.0.0" maxlength="100"><label for="artifact-name">Artifact name</label><input id="artifact-name" required maxlength="300"><label for="artifact-content">Artifact text</label><textarea id="artifact-content" required maxlength="1000000"></textarea><button type="submit">Run published deterministic checks</button><p id="compliance-status" role="status" aria-live="polite"></p></form>
<section aria-labelledby="findings-heading"><h2 id="findings-heading">Findings</h2><div id="finding-list"><p>No evaluation run yet.</p></div></section>
<section aria-labelledby="campaign-heading"><h2 id="campaign-heading">Campaign</h2><p>Evaluated artifacts from this session can be bound into one exact campaign result.</p><form id="campaign-form"><label for="campaign-name">Campaign name</label><input id="campaign-name" required maxlength="300"><button type="submit">Evaluate campaign</button><p id="campaign-status" role="status" aria-live="polite"></p></form></section>
<section aria-labelledby="exceptions-heading"><h2 id="exceptions-heading">Exceptions and evidence</h2><p>Exceptions stay visible, expire automatically, and never erase the underlying finding.</p>
<form id="exception-form"><label for="exception-rule">Rule ID</label><input id="exception-rule" required value="rule.copy.maximum-length"><label for="exception-artifact">Artifact ID</label><input id="exception-artifact" required><label for="exception-expiration">Expires</label><input id="exception-expiration" type="datetime-local" required><label for="exception-rationale">Rationale</label><input id="exception-rationale" required maxlength="300"><button type="submit">Approve exception</button><p id="exception-status" role="status" aria-live="polite"></p></form>
<h3>Register evidence</h3><form id="evidence-form"><label for="evidence-artifact">Artifact ID</label><input id="evidence-artifact" required><label for="evidence-level">Verification level</label><select id="evidence-level"><option value="owner">Owner</option><option value="professional">Professional</option></select><label for="evidence-claim">Claim</label><input id="evidence-claim" required maxlength="10000"><label for="evidence-verifier">Verifier name</label><input id="evidence-verifier" required maxlength="300"><label for="evidence-qualifications">Qualifications (professional)</label><input id="evidence-qualifications" maxlength="300"><label for="evidence-scope">Scope (professional)</label><input id="evidence-scope" maxlength="300"><label for="evidence-date">Verification date (professional)</label><input id="evidence-date" type="date"><button type="submit">Register evidence</button><p id="evidence-status" role="status" aria-live="polite"></p></form></section>
</main></body></html>"""
