"""Safe dependency-free behavior for living-brand workshop pages."""

# JavaScript stays dependency-free and uses text-only DOM APIs.
# ruff: noqa: E501

WORKSHOP_SCRIPT = r""""use strict";
const page=document.body.dataset.page,brandId=document.body.dataset.brandId;let draft=null,selected=null,currentRun=null;
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node};
function message(id,text){document.getElementById(id).textContent=text}
async function index(){const root=document.getElementById("workspace-list");try{const data=await(await fetch("/api/brand-systems?page=1&pageSize=100")).json();root.replaceChildren();const grid=el("div");grid.className="workspace-grid";for(const item of data.items){const card=el("article");card.className="workspace-card";const link=el("a",item.brand_name);link.href=`/brand-systems/${encodeURIComponent(item.brand_id)}`;card.append(link,el("p",`${item.complete_section_count} of ${item.section_count} sections reviewed`));grid.append(card)}root.append(grid);root.setAttribute("aria-busy","false")}catch{root.replaceChildren(el("p","Could not load workspaces."))}}
document.getElementById("workspace-form")?.addEventListener("submit",async event=>{event.preventDefault();message("workspace-status","Creating…");const response=await fetch("/api/brand-systems",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand_name:document.getElementById("workspace-name").value,owner_name:document.getElementById("owner-name").value})});if(response.ok){const data=await response.json();location.href=`/brand-systems/${encodeURIComponent(data.brand_id)}`}else message("workspace-status","Could not create workspace.")});
function choose(section){selected=section;document.getElementById("section-title").textContent=section.title;document.getElementById("section-status").value=section.status;const root=document.getElementById("block-editors");root.replaceChildren();section.blocks.forEach((block,i)=>{const wrap=el("div");wrap.className="block-editor";const label=el("label",`${block.type.replaceAll("_"," ")} content`);const area=el("textarea",block.text);area.id=`block-${i}`;label.htmlFor=area.id;area.addEventListener("input",()=>{block.text=area.value});wrap.append(label,area);root.append(wrap)})}
async function workshop(){try{draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();document.getElementById("brand-title").textContent=draft.brand_name;document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;const nav=document.getElementById("section-navigation");for(const section of draft.sections){const button=el("button",`${section.title} — ${section.status}`);button.type="button";button.addEventListener("click",()=>choose(section));nav.append(button)}choose(draft.sections[0])}catch{message("editor-status","Could not load this workspace.")}}
function showRun(run){currentRun=run;message("generation-status",`Generation ${run.status}: ${run.cursor} of ${run.sections.length} sections accepted.`);const list=document.getElementById("generation-progress");list.replaceChildren();for(const section of run.sections)list.append(el("li",`${section.section_id.replace("section.","")} — ${section.status}`));const active=!["completed","cancelled","failed"].includes(run.status);document.getElementById("pause-generation").disabled=!active;document.getElementById("cancel-generation").disabled=!active}
async function startGeneration(target){message("generation-status","Starting generation…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/generation-runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_section_id:target})});if(!response.ok){message("generation-status","Could not start generation.");return}showRun(await response.json());const resumed=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/resume`,{method:"POST"});if(resumed.ok){showRun(await resumed.json());draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();selected=draft.sections.find(item=>item.id===selected.id);choose(selected);document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`}else message("generation-status","Generation could not continue. Retry when ready.")}
document.getElementById("generate-complete")?.addEventListener("click",()=>startGeneration(null));
document.getElementById("generate-section")?.addEventListener("click",()=>startGeneration(selected.id));
async function control(command){if(!currentRun)return;const response=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/${command}`,{method:"POST"});if(response.ok)showRun(await response.json())}
document.getElementById("pause-generation")?.addEventListener("click",()=>control("pause"));
document.getElementById("cancel-generation")?.addEventListener("click",()=>control("cancel"));
document.getElementById("add-paragraph")?.addEventListener("click",()=>{selected.blocks.push({id:`block.${selected.id.split(".").at(-1)}.${crypto.randomUUID()}`,type:"paragraph",text:"New paragraph",references:[]});choose(selected)});
document.getElementById("section-form")?.addEventListener("submit",async event=>{event.preventDefault();selected.status=document.getElementById("section-status").value;message("editor-status","Saving…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(selected.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section:selected})});if(response.ok){draft=await response.json();selected=draft.sections.find(item=>item.id===selected.id);message("editor-status",`Saved revision ${draft.revision}.`)}else message("editor-status",response.status===409?"This draft changed. Reload before saving again.":"Could not save this section.")});
if(page==="index")index();if(page==="workshop")workshop();
"""
