"""Safe dependency-free behavior for living-brand workshop pages."""

# JavaScript stays dependency-free and uses text-only DOM APIs.
# ruff: noqa: E501

WORKSHOP_SCRIPT = r""""use strict";
const page=document.body.dataset.page,brandId=document.body.dataset.brandId,sourceBrandId=new URLSearchParams(location.search).get("sourceBrandId");let draft=null,selected=null,currentRun=null;
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node};
function message(id,text){document.getElementById(id).textContent=text}
async function index(){const root=document.getElementById("workspace-list");try{const data=await(await fetch("/api/brand-systems?page=1&pageSize=100")).json();root.replaceChildren();const grid=el("div");grid.className="workspace-grid";for(const item of data.items){const card=el("article");card.className="workspace-card";const link=el("a",item.brand_name);link.href=`/brand-systems/${encodeURIComponent(item.brand_id)}`;card.append(link,el("p",`${item.complete_section_count} of ${item.section_count} sections reviewed`));grid.append(card)}root.append(grid);root.setAttribute("aria-busy","false")}catch{root.replaceChildren(el("p","Could not load workspaces."))}}
async function prepareSourceWorkspace(){if(!sourceBrandId)return;const input=document.getElementById("workspace-name"),label=document.querySelector('label[for="workspace-name"]');input.required=false;input.disabled=true;label.textContent="Source brand kit";input.value="Loading saved kit…";try{const response=await fetch(`/api/brands/${encodeURIComponent(sourceBrandId)}`);if(!response.ok)throw new Error();const saved=await response.json();input.value=saved.kit.brand_name;message("workspace-status","This workspace will preserve the saved kit as its source.")}catch{input.value="Saved kit unavailable";message("workspace-status","Could not load the source brand kit.")}}
document.getElementById("workspace-form")?.addEventListener("submit",async event=>{event.preventDefault();message("workspace-status","Creating…");const context=document.getElementById("brand-context").value.trim();const response=await fetch("/api/brand-systems",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand_name:sourceBrandId?null:document.getElementById("workspace-name").value,brand_context:context||null,owner_name:document.getElementById("owner-name").value,source_brand_id:sourceBrandId||null})});if(response.ok){const data=await response.json();location.href=`/brand-systems/${encodeURIComponent(data.brand_id)}`}else message("workspace-status","Could not create workspace.")});
function choose(section){selected=section;document.getElementById("section-title").textContent=section.title;document.getElementById("section-status").value=section.status;const root=document.getElementById("block-editors");root.replaceChildren();section.blocks.forEach((block,i)=>{const wrap=el("div");wrap.className="block-editor";const label=el("label",`${block.type.replaceAll("_"," ")} content`);const area=el("textarea",block.text);area.id=`block-${i}`;label.htmlFor=area.id;area.addEventListener("input",()=>{block.text=area.value});wrap.append(label,area);root.append(wrap)})}
async function workshop(){try{draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();document.getElementById("brand-title").textContent=draft.brand_name;document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;const bible=el("a","View complete brand bible");bible.href=`/brand-systems/${encodeURIComponent(brandId)}/bible`;document.querySelector(".workshop-head").append(bible);const nav=document.getElementById("section-navigation");for(const section of draft.sections){const button=el("button",`${section.title} — ${section.status}`);button.type="button";button.addEventListener("click",()=>choose(section));nav.append(button)}const wanted=decodeURIComponent(location.hash.slice(1));choose(draft.sections.find(s=>s.id===wanted)||draft.sections[0])}catch{message("editor-status","Could not load this workspace.")}}
function showRun(run){currentRun=run;message("generation-status",`Generation ${run.status}: ${run.cursor} of ${run.sections.length} sections accepted.`);const list=document.getElementById("generation-progress");list.replaceChildren();for(const section of run.sections)list.append(el("li",`${section.section_id.replace("section.","")} — ${section.status}`));const active=!["completed","cancelled","failed"].includes(run.status);document.getElementById("pause-generation").disabled=!active;document.getElementById("cancel-generation").disabled=!active}
async function startGeneration(target){message("generation-status","Starting generation…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/generation-runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_section_id:target})});if(!response.ok){message("generation-status","Could not start generation.");return}showRun(await response.json());const resumed=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/resume`,{method:"POST"});if(resumed.ok){showRun(await resumed.json());draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();selected=draft.sections.find(item=>item.id===selected.id);choose(selected);document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`}else message("generation-status","Generation could not continue. Retry when ready.")}
document.getElementById("generate-complete")?.addEventListener("click",()=>startGeneration(null));
document.getElementById("generate-section")?.addEventListener("click",()=>startGeneration(selected.id));
async function control(command){if(!currentRun)return;const response=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/${command}`,{method:"POST"});if(response.ok)showRun(await response.json())}
document.getElementById("pause-generation")?.addEventListener("click",()=>control("pause"));
document.getElementById("cancel-generation")?.addEventListener("click",()=>control("cancel"));
document.getElementById("add-paragraph")?.addEventListener("click",()=>{selected.blocks.push({id:`block.${selected.id.split(".").at(-1)}.${crypto.randomUUID()}`,type:"paragraph",text:"New paragraph",references:[]});choose(selected)});
document.getElementById("section-form")?.addEventListener("submit",async event=>{event.preventDefault();selected.status=document.getElementById("section-status").value;message("editor-status","Saving…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(selected.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section:selected})});if(response.ok){draft=await response.json();selected=draft.sections.find(item=>item.id===selected.id);message("editor-status",`Saved revision ${draft.revision}.`)}else message("editor-status",response.status===409?"This draft changed. Reload before saving again.":"Could not save this section.")});
document.getElementById("print-bible")?.addEventListener("click",()=>window.print());
let editing=false;
function setEditable(on){document.querySelectorAll('.bible-section[data-locked="0"] [data-block-id]').forEach(node=>{node.contentEditable=on?"true":"false";node.classList.toggle("editable",on)})}
async function bible(){const button=document.getElementById("edit-bible");button.disabled=true;try{draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();button.disabled=false}catch{message("edit-status","In-place editing is unavailable right now.");return}
const picker=document.getElementById("font-picker");
button.addEventListener("click",()=>{editing=!editing;button.setAttribute("aria-pressed",String(editing));button.textContent=editing?"Done editing":"Edit in place";setEditable(editing);if(picker)picker.hidden=!editing;message("edit-status",editing?"Editing prose. Changes save when you click out of a block. Locked sections and non-prose content stay in the workshop.":"")});
function ensureFontLink(family){const id="gf-"+family.replace(/[^a-z0-9]+/gi,"-");if(document.getElementById(id))return;const link=el("link");link.id=id;link.rel="stylesheet";link.href="https://fonts.googleapis.com/css2?family="+family.replace(/ /g,"+")+"&display=swap";document.head.append(link)}
document.querySelectorAll("#font-picker select").forEach(select=>select.addEventListener("change",async()=>{const value=select.value,varName=select.dataset.var;if(value){ensureFontLink(value.split("'")[1]);document.documentElement.style.setProperty(varName,value)}else document.documentElement.style.removeProperty(varName);const typo=draft.sections.find(s=>s.id==="section.typography");if(!typo){message("edit-status","No typography section to store fonts in.");return}const tokenId=select.dataset.tokenId;typo.tokens=typo.tokens.filter(t=>t.id!==tokenId);if(value)typo.tokens.push({id:tokenId,name:select.dataset.tokenName,value_type:"font",value,references:[]});message("edit-status","Saving font…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(typo.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section:typo})});if(response.ok){draft=await response.json();message("edit-status",`Saved revision ${draft.revision}.`)}else message("edit-status",response.status===409?"This brand changed elsewhere. Reload before editing again.":"Could not save the font.")}));
document.addEventListener("focusout",async event=>{const node=event.target;if(!editing||!node.dataset||!node.dataset.blockId)return;const sectionEl=node.closest("[data-section-id]");const section=draft.sections.find(s=>s.id===sectionEl.dataset.sectionId);const block=section&&section.blocks.find(b=>b.id===node.dataset.blockId);if(!block)return;const text=node.innerText.replace(/\n$/,"");if(text===block.text)return;block.text=text;message("edit-status","Saving…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(section.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section})});if(response.ok){draft=await response.json();message("edit-status",`Saved revision ${draft.revision}.`)}else{message("edit-status",response.status===409?"This brand changed elsewhere. Reload before editing again.":"Could not save — copy your text before reloading.")}})}
if(page==="index"){index();prepareSourceWorkspace()}if(page==="workshop")workshop();if(page==="bible")bible();
"""
