"""Safe dependency-free behavior for living-brand workshop pages."""

# JavaScript stays dependency-free and uses text-only DOM APIs.
# ruff: noqa: E501

WORKSHOP_SCRIPT = r""""use strict";
const page=document.body.dataset.page,brandId=document.body.dataset.brandId,sourceBrandId=new URLSearchParams(location.search).get("sourceBrandId");let draft=null,selected=null,currentRun=null,saveTimer=null,dirty=false,saving=false;const pendingSectionSaves=new Map();
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node};
function message(id,text){document.getElementById(id).textContent=text}
function markDirty(){if(selected){selected.status=document.getElementById("section-status").value;pendingSectionSaves.set(selected.id,JSON.parse(JSON.stringify(selected)))}dirty=true;message("editor-status","Unsaved changes…");if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(performAutosave,800)}
async function performAutosave(){if(saving||pendingSectionSaves.size===0)return;if(saveTimer){clearTimeout(saveTimer);saveTimer=null}saving=true;message("editor-status","Saving…");const[targetId,sectionToSave]=pendingSectionSaves.entries().next().value;pendingSectionSaves.delete(targetId);try{const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(targetId)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section:sectionToSave})});if(response.ok){draft=await response.json();document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;if(pendingSectionSaves.size===0){dirty=false;message("editor-status",`Saved revision ${draft.revision}.`)}}else{if(!pendingSectionSaves.has(targetId))pendingSectionSaves.set(targetId,sectionToSave);message("editor-status",response.status===409?"This draft changed. Reload before saving again.":"Could not save this section — check required fields.")}}catch{if(!pendingSectionSaves.has(targetId))pendingSectionSaves.set(targetId,sectionToSave);message("editor-status","Network error saving — retrying shortly.")}finally{saving=false;if(pendingSectionSaves.size>0)saveTimer=setTimeout(performAutosave,1000)}}
window.addEventListener("beforeunload",event=>{if(dirty||saving||pendingSectionSaves.size>0){event.preventDefault();event.returnValue=""}});
async function index(){const root=document.getElementById("workspace-list");try{const data=await(await fetch("/api/brand-systems?page=1&pageSize=100")).json();root.replaceChildren();const grid=el("div");grid.className="workspace-grid";for(const item of data.items){const card=el("article");card.className="workspace-card";const link=el("a",item.brand_name);link.href=`/brand-systems/${encodeURIComponent(item.brand_id)}`;card.append(link,el("p",`${item.complete_section_count} of ${item.section_count} sections reviewed`));grid.append(card)}root.append(grid);root.setAttribute("aria-busy","false")}catch{root.replaceChildren(el("p","Could not load workspaces."))}}
async function prepareSourceWorkspace(){if(!sourceBrandId)return;const input=document.getElementById("workspace-name"),label=document.querySelector('label[for="workspace-name"]');input.required=false;input.disabled=true;label.textContent="Source brand kit";input.value="Loading saved kit…";try{const response=await fetch(`/api/brands/${encodeURIComponent(sourceBrandId)}`);if(!response.ok)throw new Error();const saved=await response.json();input.value=saved.kit.brand_name;message("workspace-status","This workspace will preserve the saved kit as its source.")}catch{input.value="Saved kit unavailable";message("workspace-status","Could not load the source brand kit.")}}
document.getElementById("workspace-form")?.addEventListener("submit",async event=>{event.preventDefault();message("workspace-status","Creating…");const context=document.getElementById("brand-context").value.trim();const response=await fetch("/api/brand-systems",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand_name:sourceBrandId?null:document.getElementById("workspace-name").value,brand_context:context||null,owner_name:document.getElementById("owner-name").value,source_brand_id:sourceBrandId||null})});if(response.ok){const data=await response.json();location.href=`/brand-systems/${encodeURIComponent(data.brand_id)}`}else message("workspace-status","Could not create workspace.")});
const PATTERN_KINDS=["positioning_framework","audience_profile","message_hierarchy","content_template","say_never_say","voice_scale","logo_lockup","logo_clear_space","color_application","type_scale","layout_template","image_art_direction","icon_system","motion_behavior","sound_direction","web_component","interaction_pattern","channel_playbook","accessibility_checklist","governance_workflow"];
const TOKEN_TYPES=["color","string","number","dimension","duration","font","boolean"];
function slug(){return selected.id.split(".").at(-1)}
function labeledField(labelText,tag,value,onInput,options,placeholder){const label=el("label");label.append(document.createTextNode(labelText));let control;if(tag==="select"){control=el("select");for(const opt of options){const o=el("option",opt.replaceAll("_"," "));o.value=opt;if(opt===value)o.selected=true;control.append(o)}control.addEventListener("change",()=>{onInput(control.value);markDirty()})}else{control=el(tag);control.value=value;if(placeholder)control.placeholder=placeholder;control.addEventListener("input",()=>{onInput(control.value);markDirty()})}label.append(control);return label}
function removeButton(text,onClick){const b=el("button",text);b.type="button";b.className="remove";b.addEventListener("click",()=>{onClick();markDirty()});return b}
function stringList(title,arr,rerender,placeholder){const box=el("div");box.className="subgroup";box.append(el("p",title));arr.forEach((val,i)=>{const row=el("div");row.className="spec-row";const input=el("input");input.value=val;if(placeholder)input.placeholder=placeholder;input.addEventListener("input",()=>{arr[i]=input.value;markDirty()});row.append(input);if(arr.length>1)row.append(removeButton("Remove",()=>{arr.splice(i,1);rerender();markDirty()}));box.append(row)});const add=el("button",`Add ${title.toLowerCase()} item`);add.type="button";add.addEventListener("click",()=>{arr.push("");rerender();markDirty()});box.append(add);return box}
function renderInto(id,items,build){const root=document.getElementById(id);if(!root)return;root.replaceChildren();items.forEach((item,i)=>root.append(build(item,i)))}
function renderBlocks(){renderInto("block-editors",selected.blocks,(block,i)=>{const wrap=el("div");wrap.className="block-editor";wrap.append(labeledField(`${block.type.replaceAll("_"," ")} content`,"textarea",block.text,v=>block.text=v,undefined,"e.g. Our voice is plain-spoken and specific. We earn trust by naming trade-offs, not hiding them."),removeButton("Remove paragraph",()=>{selected.blocks.splice(i,1);renderBlocks();markDirty()}));return wrap})}
function renderRules(){renderInto("rule-editors",selected.rules,(rule,i)=>{const card=el("div");card.className="item-editor";card.append(labeledField("Name","input",rule.name,v=>rule.name=v,undefined,"e.g. Never fake urgency"),labeledField("Description","textarea",rule.description,v=>rule.description=v,undefined,"e.g. Countdown timers must reflect a real deadline. No 'ends tonight' that resets daily."),labeledField("Enforcement","select",rule.enforcement,v=>rule.enforcement=v,["advisory","warning","blocking"]),removeButton("Remove rule",()=>{selected.rules.splice(i,1);renderRules();markDirty()}));return card})}
function renderTokens(){renderInto("token-editors",selected.tokens,(token,i)=>{const card=el("div");card.className="item-editor";card.append(labeledField("Name","input",token.name,v=>token.name=v,undefined,"e.g. Primary color, Body font"),labeledField("Type","select",token.value_type,v=>token.value_type=v,TOKEN_TYPES),labeledField("Value","input",String(token.value),v=>token.value=v,undefined,"e.g. #1a1a1a for color, or Inter for font"),removeButton("Remove token",()=>{selected.tokens.splice(i,1);renderTokens();markDirty()}));return card})}
function renderExamples(){renderInto("example-editors",selected.examples,(ex,i)=>{const card=el("div");card.className="item-editor";card.append(labeledField("Kind","select",ex.kind,v=>ex.kind=v,["do","dont","context"]),labeledField("Text","textarea",ex.text,v=>ex.text=v,undefined,"e.g. Don't: 'Leverage synergies to unlock value.' Do: 'Help your team share what works.'"),removeButton("Remove example",()=>{selected.examples.splice(i,1);renderExamples();markDirty()}));return card})}
function renderPatterns(){renderInto("pattern-editors",selected.patterns,(p,i)=>{const card=el("div");card.className="item-editor";card.append(labeledField("Name","input",p.name,v=>p.name=v,undefined,"e.g. Say / never say"),labeledField("Kind","select",p.kind,v=>p.kind=v,PATTERN_KINDS),labeledField("Summary","textarea",p.summary,v=>p.summary=v,undefined,"e.g. Turns the voice into concrete word choices anyone can apply."));const specs=el("div");specs.className="subgroup";specs.append(el("p","Specifications"));p.specifications.forEach((s,si)=>{const row=el("div");row.className="spec-row";row.append(labeledField("Label","input",s.label,v=>s.label=v,undefined,"e.g. Say"),labeledField("Value","textarea",s.value,v=>s.value=v,undefined,"e.g. Plain, direct, human words"));if(p.specifications.length>1)row.append(removeButton("Remove",()=>{p.specifications.splice(si,1);renderPatterns();markDirty()}));specs.append(row)});const addSpec=el("button","Add specification");addSpec.type="button";addSpec.addEventListener("click",()=>{p.specifications.push({label:"",value:""});renderPatterns();markDirty()});specs.append(addSpec);card.append(specs,stringList("Do",p.do_guidance,renderPatterns,"e.g. Use verbs people say out loud"),stringList("Do not",p.dont_guidance,renderPatterns,"e.g. Reach for corporate abstractions"),removeButton("Remove pattern",()=>{selected.patterns.splice(i,1);renderPatterns();markDirty()}));return card})}
function choose(section){if(dirty&&selected){selected.status=document.getElementById("section-status").value;pendingSectionSaves.set(selected.id,JSON.parse(JSON.stringify(selected)));performAutosave()}selected=section;document.getElementById("section-title").textContent=section.title;document.getElementById("section-status").value=section.status;renderBlocks();renderRules();renderTokens();renderExamples();renderPatterns()}
async function workshop(){try{draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();document.getElementById("brand-title").textContent=draft.brand_name;document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;const bible=el("a","View complete brand bible");bible.href=`/brand-systems/${encodeURIComponent(brandId)}/bible`;document.querySelector(".workshop-head").append(bible);const nav=document.getElementById("section-navigation");for(const section of draft.sections){const button=el("button",`${section.title} — ${section.status}`);button.type="button";button.addEventListener("click",()=>choose(section));nav.append(button)}const wanted=decodeURIComponent(location.hash.slice(1));choose(draft.sections.find(s=>s.id===wanted)||draft.sections[0]);renderAssets()}catch{message("editor-status","Could not load this workspace.")}}
function renderAssets(){const list=document.getElementById("asset-list");if(!list)return;list.replaceChildren();if(!draft.assets.length)list.append(el("li","No production assets uploaded yet."));for(const asset of draft.assets){const kb=Math.max(1,Math.round(asset.size_bytes/1024));list.append(el("li",`${asset.name} — ${asset.media_type}, ${kb} KB${asset.required?"":" (optional)"}`))}const source=document.getElementById("derivative-source");if(!source)return;const prior=source.value;source.replaceChildren();const empty=el("option","Choose a raster logo");empty.value="";source.append(empty);for(const asset of draft.assets.filter(item=>["image/gif","image/jpeg","image/png","image/webp"].includes(item.media_type))){const option=el("option",asset.name);option.value=asset.id;source.append(option)}if([...source.options].some(option=>option.value===prior))source.value=prior}
document.getElementById("logo-form")?.addEventListener("submit",async event=>{event.preventDefault();message("logo-status","Generating… this can take up to a minute.");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/logo-generations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,instructions:document.getElementById("logo-instructions").value})});if(response.ok){draft=await response.json();document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;renderAssets();message("logo-status","Logo added to your assets.")}else message("logo-status",response.status===409?"This draft changed elsewhere. Reload before generating again.":response.status===503?"Image generation isn't configured on the server.":response.status===422?"The image model declined that request. Try different instructions.":"Could not generate a logo right now.")});
document.getElementById("asset-form")?.addEventListener("submit",async event=>{event.preventDefault();const fileInput=document.getElementById("asset-file");if(!fileInput.files.length){message("asset-status","Choose a file first.");return}const body=new FormData();body.append("expected_revision",draft.revision);body.append("name",document.getElementById("asset-name").value);body.append("required",document.getElementById("asset-required").checked);body.append("file",fileInput.files[0]);message("asset-status","Uploading…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/asset-uploads`,{method:"POST",body});if(response.ok){draft=await response.json();document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;event.target.reset();renderAssets();message("asset-status","Uploaded.")}else message("asset-status",response.status===409?"This draft changed elsewhere. Reload before uploading again.":response.status===413?"That file is too large.":response.status===422?"That file type is not accepted.":"Could not upload that file.")});
async function createDerivatives(resource,label,body={}){const source=document.getElementById("derivative-source").value;if(!source){message("derivative-status","Choose a raster logo first.");return}const buttons=document.querySelectorAll(".derivative-tools button");buttons.forEach(button=>button.disabled=true);message("derivative-status",`${label}…`);try{const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/assets/${encodeURIComponent(source)}/${resource}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,...body})});if(response.ok){draft=await response.json();document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`;renderAssets();message("derivative-status",`${label} complete. New assets are ready.`)}else message("derivative-status",response.status===409?"This draft changed elsewhere. Reload before creating derivatives.":response.status===404?"That source asset no longer exists.":response.status===422?"That logo could not be processed. Choose a valid raster logo.":response.status===503?"AI image editing is unavailable right now.":"Could not create those derivatives.")}finally{buttons.forEach(button=>button.disabled=false)}}
document.getElementById("create-favicon-set")?.addEventListener("click",()=>createDerivatives("favicon-sets","Creating favicon and app icons"));
document.getElementById("create-vector")?.addEventListener("click",()=>createDerivatives("vectorizations","Vectorizing logo"));
document.getElementById("create-logo-variants")?.addEventListener("click",()=>{const variants=[...document.querySelectorAll('input[name="logo-variant"]:checked')].map(input=>input.value);if(!variants.length){message("derivative-status","Select at least one AI variant.");return}createDerivatives("logo-variant-sets","Creating AI logo variants",{variants})});
function showRun(run){currentRun=run;message("generation-status",`Generation ${run.status}: ${run.cursor} of ${run.sections.length} sections accepted.`);const list=document.getElementById("generation-progress");list.replaceChildren();for(const section of run.sections)list.append(el("li",`${section.section_id.replace("section.","")} — ${section.status}`));const active=!["completed","cancelled","failed"].includes(run.status);document.getElementById("pause-generation").disabled=!active;document.getElementById("cancel-generation").disabled=!active}
async function startGeneration(target){message("generation-status","Starting generation…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/generation-runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_section_id:target})});if(!response.ok){message("generation-status","Could not start generation.");return}showRun(await response.json());const resumed=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/resume`,{method:"POST"});if(resumed.ok){showRun(await resumed.json());draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();selected=draft.sections.find(item=>item.id===selected.id);choose(selected);document.getElementById("revision-label").textContent=`Draft revision ${draft.revision}`}else message("generation-status","Generation could not continue. Retry when ready.")}
document.getElementById("generate-complete")?.addEventListener("click",()=>startGeneration(null));
document.getElementById("generate-section")?.addEventListener("click",()=>startGeneration(selected.id));
async function control(command){if(!currentRun)return;const response=await fetch(`/api/generation-runs/${encodeURIComponent(currentRun.id)}/${command}`,{method:"POST"});if(response.ok)showRun(await response.json())}
document.getElementById("pause-generation")?.addEventListener("click",()=>control("pause"));
document.getElementById("cancel-generation")?.addEventListener("click",()=>control("cancel"));
function newId(kind){return `${kind}.${slug()}.${crypto.randomUUID()}`}
document.getElementById("add-paragraph")?.addEventListener("click",()=>{selected.blocks.push({id:newId("block"),type:"paragraph",text:"",references:[]});renderBlocks();markDirty()});
document.getElementById("add-rule")?.addEventListener("click",()=>{selected.rules.push({id:newId("rule"),name:"",description:"",enforcement:"advisory",references:[]});renderRules();markDirty()});
document.getElementById("add-token")?.addEventListener("click",()=>{selected.tokens.push({id:newId("token"),name:"",value_type:"color",value:"",references:[]});renderTokens();markDirty()});
document.getElementById("add-example")?.addEventListener("click",()=>{selected.examples.push({id:newId("example"),kind:"do",text:"",references:[]});renderExamples();markDirty()});
document.getElementById("add-pattern")?.addEventListener("click",()=>{selected.patterns.push({id:newId("pattern"),name:"",kind:"content_template",summary:"",specifications:[{label:"",value:""}],do_guidance:[""],dont_guidance:[""],references:[]});renderPatterns();markDirty()});
document.getElementById("section-status")?.addEventListener("change",markDirty);
document.getElementById("section-form")?.addEventListener("submit",async event=>{event.preventDefault();performAutosave()});
document.getElementById("print-bible")?.addEventListener("click",()=>window.print());
let editing=false;
function setEditable(on){document.querySelectorAll('.bible-section[data-locked="0"] [data-block-id]').forEach(node=>{node.contentEditable=on?"true":"false";node.classList.toggle("editable",on)})}
async function bible(){const button=document.getElementById("edit-bible");button.disabled=true;try{draft=await(await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}`)).json();button.disabled=false}catch{message("edit-status","In-place editing is unavailable right now.");return}
const exportBtn=document.getElementById("export-menu-btn"),exportMenu=document.getElementById("export-menu");if(exportBtn&&exportMenu){exportBtn.addEventListener("click",e=>{e.stopPropagation();exportMenu.hidden=!exportMenu.hidden});document.addEventListener("click",e=>{if(!exportMenu.contains(e.target)&&e.target!==exportBtn)exportMenu.hidden=true})}
const picker=document.getElementById("font-picker");
button.addEventListener("click",()=>{editing=!editing;button.setAttribute("aria-pressed",String(editing));button.textContent=editing?"Done editing":"Edit in place";setEditable(editing);if(picker)picker.hidden=!editing;message("edit-status",editing?"Editing prose. Changes save when you click out of a block. Locked sections and non-prose content stay in the workshop.":"")});
function ensureFontLink(family){const id="gf-"+family.replace(/[^a-z0-9]+/gi,"-");if(document.getElementById(id))return;const link=el("link");link.id=id;link.rel="stylesheet";link.href="https://fonts.googleapis.com/css2?family="+family.replace(/ /g,"+")+"&display=swap";document.head.append(link)}
document.querySelectorAll("#font-picker select").forEach(select=>select.addEventListener("change",async()=>{const value=select.value,varName=select.dataset.var;if(value){ensureFontLink(value.split("'")[1]);document.documentElement.style.setProperty(varName,value)}else document.documentElement.style.removeProperty(varName);const typo=draft.sections.find(s=>s.id==="section.typography");if(!typo){message("edit-status","No typography section to store fonts in.");return}const tokenId=select.dataset.tokenId;typo.tokens=typo.tokens.filter(t=>t.id!==tokenId);if(value)typo.tokens.push({id:tokenId,name:select.dataset.tokenName,value_type:"font",value,references:[]});message("edit-status","Saving font…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(typo.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section:typo})});if(response.ok){draft=await response.json();message("edit-status",`Saved revision ${draft.revision}.`)}else message("edit-status",response.status===409?"This brand changed elsewhere. Reload before editing again.":"Could not save the font.")}));
document.addEventListener("focusout",async event=>{const node=event.target;if(!editing||!node.dataset||!node.dataset.blockId)return;const sectionEl=node.closest("[data-section-id]");const section=draft.sections.find(s=>s.id===sectionEl.dataset.sectionId);const block=section&&section.blocks.find(b=>b.id===node.dataset.blockId);if(!block)return;const text=node.innerText.replace(/\n$/,"");if(text===block.text)return;block.text=text;message("edit-status","Saving…");const response=await fetch(`/api/brand-systems/${encodeURIComponent(brandId)}/sections/${encodeURIComponent(section.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_revision:draft.revision,section})});if(response.ok){draft=await response.json();message("edit-status",`Saved revision ${draft.revision}.`)}else{message("edit-status",response.status===409?"This brand changed elsewhere. Reload before editing again.":"Could not save — copy your text before reloading.")}})}
if(page==="index"){index();prepareSourceWorkspace()}if(page==="workshop")workshop();if(page==="bible")bible();
"""
